// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments)]
use serde::Serialize;

use crate::error::Result;
use crate::Bot;

impl Bot {
    /// Use this method to get the number of members in a chat. Returns Int on success.
    /// <https://core.telegram.org/bots/api#getchatmembercount>
    pub fn get_chat_member_count(&self, chat_id: i64) -> GetChatMemberCountBuilder {
        GetChatMemberCountBuilder::new(self, chat_id)
    }
}

#[derive(Serialize)]
pub struct GetChatMemberCountBuilder<'a> {
    #[serde(skip)]
    bot: &'a Bot,
    /// Unique identifier for the target chat or username of the target supergroup or channel (in the format @channelusername)
    pub chat_id: i64,
}

impl<'a> GetChatMemberCountBuilder<'a> {
    pub fn new(bot: &'a Bot, chat_id: i64) -> Self {
        Self { bot, chat_id }
    }

    pub fn chat_id(mut self, chat_id: i64) -> Self {
        self.chat_id = chat_id;
        self
    }

    pub async fn send(self) -> Result<i64> {
        let form = serde_json::to_value(&self)?;
        self.bot.get::<i64>("getChatMemberCount", Some(&form)).await
    }
}
