// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments)]
use serde::Serialize;

use crate::Bot;
use crate::error::Result;

impl Bot {
    /// Use this method to set the title of a created sticker set. Returns True on success.
    /// <https://core.telegram.org/bots/api#setstickersettitle>
    pub fn set_sticker_set_title(&self, name: String, title: String) -> SetStickerSetTitleBuilder {
        SetStickerSetTitleBuilder::new(self, name, title)
    }
}

#[derive(Serialize)]
pub struct SetStickerSetTitleBuilder<'a> {
    #[serde(skip)]
    bot: &'a Bot,
    /// Sticker set name
    pub name: String,
    /// Sticker set title, 1-64 characters
    pub title: String,
}


impl <'a> SetStickerSetTitleBuilder<'a> {
    pub fn new(bot: &'a Bot, name: String, title: String) -> Self {
        Self{
            bot,
            name,
            title,
        }
    }

    pub fn name(mut self, name: String) -> Self {
        self.name = name;
        self
    }
                
    pub fn title(mut self, title: String) -> Self {
        self.title = title;
        self
    }
                
    pub async fn send(self) -> Result<bool> {
        let form = serde_json::to_value(&self)?;
        self.bot.get::<bool>("setStickerSetTitle", Some(&form)).await
    }

}