blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/ferrisgram/ferrisgram/discussions
    about: You can ask questions related to usage on github here.
  - name: Telegram Group
    url: https://telegram.me/ferrisgramsupport
    about: Telegram support group for the ferrisgram library for faster replies.
