// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Animation;

impl Animation {
    /// This function creates an empty struct for the object Animation.
    pub fn new(
        file_id: String,
        file_unique_id: String,
        width: i64,
        height: i64,
        duration: i64,
    ) -> Self {
        Self {
            file_id,
            file_unique_id,
            width,
            height,
            duration,
            thumbnail: None,
            file_name: None,
            mime_type: None,
            file_size: None,
        }
    }
}
