// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotName;

impl BotName {
    /// This function creates an empty struct for the object BotName.
    pub fn new() -> Self {
        Self {
            name: "".to_string(),
        }
    }
}
impl Default for BotName {
    fn default() -> Self {
        Self::new()
    }
}
