// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotShortDescription;

impl BotShortDescription {
    /// This function creates an empty struct for the object BotShortDescription.
    pub fn new() -> Self {
        Self {
            short_description: "".to_string(),
        }
    }
}
impl Default for BotShortDescription {
    fn default() -> Self {
        Self::new()
    }
}
