// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommandScopeAllChatAdministrators;

impl Default for BotCommandScopeAllChatAdministrators {
    fn default() -> Self {
        Self::new()
    }
}

impl BotCommandScopeAllChatAdministrators {
    /// This function creates an empty struct for the object BotCommandScopeAllChatAdministrators.
    pub fn new() -> Self {
        Self {}
    }
}
