// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotDescription;

impl BotDescription {
    /// This function creates an empty struct for the object BotDescription.
    pub fn new(description: String) -> Self {
        Self {
            description,
        }
    }
}