// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommand;

impl BotCommand {
    /// This function creates an empty struct for the object BotCommand.
    pub fn new() -> Self {
        Self {
            command: "".to_string(),
            description: "".to_string(),
        }
    }
}
impl Default for BotCommand {
    fn default() -> Self {
        Self::new()
    }
}