// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BotCommandScopeAllPrivateChats;

impl BotCommandScopeAllPrivateChats {
    /// This function creates an empty struct for the object BotCommandScopeAllPrivateChats.
    pub fn new() -> Self {
        Self {}
    }
}
