// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommandScope;
use crate::types::BotCommandScopeDefault;

impl BotCommandScope {
    /// This function creates an empty struct for the enum BotCommandScope.
    pub fn new() -> Self {
        Self::BotCommandScopeDefault(BotCommandScopeDefault::new())
    }

}
impl Default for BotCommandScope {
    fn default() -> Self {
        Self::new()
    }
}