// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BotShortDescription;

impl BotShortDescription {
    /// This function creates an empty struct for the object BotShortDescription.
    pub fn new(short_description: String) -> Self {
        Self { short_description }
    }
}
