// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BotCommandScopeChatAdministrators;

impl BotCommandScopeChatAdministrators {
    /// This function creates an empty struct for the object BotCommandScopeChatAdministrators.
    pub fn new(chat_id: i64) -> Self {
        Self { chat_id }
    }
}
