// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommandScopeAllPrivateChats;

impl BotCommandScopeAllPrivateChats {
    /// This function creates an empty struct for the object BotCommandScopeAllPrivateChats.
    pub fn new(r#type: String) -> Self {
        Self { r#type }
    }
}
