// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BotCommandScopeChatMember;

impl BotCommandScopeChatMember {
    /// This function creates an empty struct for the object BotCommandScopeChatMember.
    pub fn new(chat_id: i64, user_id: i64) -> Self {
        Self { chat_id, user_id }
    }
}
