// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommandScopeAllChatAdministrators;

impl BotCommandScopeAllChatAdministrators {
    /// This function creates an empty struct for the object BotCommandScopeAllChatAdministrators.
    pub fn new(r#type: String) -> Self {
        Self { r#type }
    }
}
