// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BotName;

impl BotName {
    /// This function creates an empty struct for the object BotName.
    pub fn new(name: String) -> Self {
        Self { name }
    }
}
