// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommand;

impl BotCommand {
    /// This function creates an empty struct for the object BotCommand.
    pub fn new(command: String, description: String) -> Self {
        Self {
            command,
            description,
        }
    }
}