// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BotCommandScopeDefault;

impl BotCommandScopeDefault {
    /// This function creates an empty struct for the object BotCommandScopeDefault.
    pub fn new(r#type: String) -> Self {
        Self { r#type }
    }
}
