// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::CallbackQuery;
use crate::types::User;

impl CallbackQuery {
    /// This function creates an empty struct for the object CallbackQuery.
    pub fn new(id: String, from: User, chat_instance: String) -> Self {
        Self {
            id,
            from,
            message: None,
            inline_message_id: None,
            chat_instance,
            data: None,
            game_short_name: None,
        }
    }
}
