// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatPhoto;

impl ChatPhoto {
    /// This function creates an empty struct for the object ChatPhoto.
    pub fn new() -> Self {
        Self {
            small_file_id: "".to_string(),
            small_file_unique_id: "".to_string(),
            big_file_id: "".to_string(),
            big_file_unique_id: "".to_string(),
        }
    }
}
impl Default for ChatPhoto {
    fn default() -> Self {
        Self::new()
    }
}