// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatBoostUpdated;
use crate::types::Chat;
use crate::types::ChatBoost;

impl ChatBoostUpdated {
    /// This function creates an empty struct for the object ChatBoostUpdated.
    pub fn new(chat: Chat, boost: ChatBoost) -> Self {
        Self {
            chat,
            boost,
        }
    }
}