// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberUpdated;
use crate::types::Chat;
use crate::types::User;
use crate::types::ChatMember;

impl ChatMemberUpdated {
    /// This function creates an empty struct for the object ChatMemberUpdated.
    pub fn new() -> Self {
        Self {
            chat: Chat::new(),
            from: User::new(),
            date: 0,
            old_chat_member: ChatMember::new(),
            new_chat_member: ChatMember::new(),
            invite_link: None,
        }
    }
}
impl Default for ChatMemberUpdated {
    fn default() -> Self {
        Self::new()
    }
}