// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatLocation;
use crate::types::Location;

impl ChatLocation {
    /// This function creates an empty struct for the object ChatLocation.
    pub fn new(location: Location, address: String) -> Self {
        Self { location, address }
    }
}
