// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMember;
use crate::types::ChatMemberOwner;

impl ChatMember {
    /// This function creates an empty struct for the enum ChatMember.
    pub fn new() -> Self {
        Self::ChatMemberOwner(ChatMemberOwner::new())
    }

}
impl Default for ChatMember {
    fn default() -> Self {
        Self::new()
    }
}