// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatShared;

impl ChatShared {
    /// This function creates an empty struct for the object ChatShared.
    pub fn new() -> Self {
        Self {
            request_id: 0,
            chat_id: 0,
        }
    }
}
impl Default for ChatShared {
    fn default() -> Self {
        Self::new()
    }
}