// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatBoostSourcePremium;
use crate::types::User;

impl ChatBoostSourcePremium {
    /// This function creates an empty struct for the object ChatBoostSourcePremium.
    pub fn new(source: String, user: User) -> Self {
        Self { source, user }
    }
}
