// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ChatBoostSourceGiftCode;
use crate::types::User;

impl ChatBoostSourceGiftCode {
    /// This function creates an empty struct for the object ChatBoostSourceGiftCode.
    pub fn new(user: User) -> Self {
        Self { user }
    }
}
