// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatLocation;
use crate::types::Location;

impl ChatLocation {
    /// This function creates an empty struct for the object ChatLocation.
    pub fn new() -> Self {
        Self {
            location: Location::new(),
            address: "".to_string(),
        }
    }
}
impl Default for ChatLocation {
    fn default() -> Self {
        Self::new()
    }
}