// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberAdministrator;
use crate::types::User;

impl ChatMemberAdministrator {
    /// This function creates an empty struct for the object ChatMemberAdministrator.
    pub fn new() -> Self {
        Self {
            user: User::new(),
            can_be_edited: false,
            is_anonymous: false,
            can_manage_chat: false,
            can_delete_messages: false,
            can_manage_video_chats: false,
            can_restrict_members: false,
            can_promote_members: false,
            can_change_info: false,
            can_invite_users: false,
            can_post_messages: None,
            can_edit_messages: None,
            can_pin_messages: None,
            custom_title: None,
        }
    }
}
impl Default for ChatMemberAdministrator {
    fn default() -> Self {
        Self::new()
    }
}