// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatBoostSourceGiftCode;
use crate::types::User;

impl ChatBoostSourceGiftCode {
    /// This function creates an empty struct for the object ChatBoostSourceGiftCode.
    pub fn new(source: String, user: User) -> Self {
        Self { source, user }
    }
}
