// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberMember;
use crate::types::User;

impl ChatMemberMember {
    /// This function creates an empty struct for the object ChatMemberMember.
    pub fn new(user: User) -> Self {
        Self {
            user,
        }
    }
}