// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatShared;

impl ChatShared {
    /// This function creates an empty struct for the object ChatShared.
    pub fn new(request_id: i64, chat_id: i64) -> Self {
        Self {
            request_id,
            chat_id,
        }
    }
}
