// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ChatLocation;
use crate::types::Location;

impl ChatLocation {
    /// This function creates an empty struct for the object ChatLocation.
    pub fn new(location: Location, address: String) -> Self {
        Self { location, address }
    }
}
