// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberMember;
use crate::types::User;

impl ChatMemberMember {
    /// This function creates an empty struct for the object ChatMemberMember.
    pub fn new() -> Self {
        Self {
            status: "".to_string(),
            user: User::new(),
        }
    }
}