// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberLeft;
use crate::types::User;

impl ChatMemberLeft {
    /// This function creates an empty struct for the object ChatMemberLeft.
    pub fn new() -> Self {
        Self {
            user: User::new(),
        }
    }
}
impl Default for ChatMemberLeft {
    fn default() -> Self {
        Self::new()
    }
}