// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Chat;
use crate::types::ChatBoost;
use crate::types::ChatBoostUpdated;

impl ChatBoostUpdated {
    /// This function creates an empty struct for the object ChatBoostUpdated.
    pub fn new(chat: Chat, boost: ChatBoost) -> Self {
        Self { chat, boost }
    }
}
