// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberOwner;
use crate::types::User;

impl ChatMemberOwner {
    /// This function creates an empty struct for the object ChatMemberOwner.
    pub fn new() -> Self {
        Self {
            user: User::new(),
            is_anonymous: false,
            custom_title: None,
        }
    }
}
impl Default for ChatMemberOwner {
    fn default() -> Self {
        Self::new()
    }
}