// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatMemberOwner;
use crate::types::User;

impl ChatMemberOwner {
    /// This function creates an empty struct for the object ChatMemberOwner.
    pub fn new(status: String, user: User, is_anonymous: bool) -> Self {
        Self {
            status,
            user,
            is_anonymous,
            custom_title: None,
        }
    }
}
