// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ChatInviteLink;
use crate::types::User;

impl ChatInviteLink {
    /// This function creates an empty struct for the object ChatInviteLink.
    pub fn new() -> Self {
        Self {
            invite_link: "".to_string(),
            creator: User::new(),
            creates_join_request: false,
            is_primary: false,
            is_revoked: false,
            name: None,
            expire_date: None,
            member_limit: None,
            pending_join_request_count: None,
        }
    }
}
impl Default for ChatInviteLink {
    fn default() -> Self {
        Self::new()
    }
}