// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Dice;

impl Dice {
    /// This function creates an empty struct for the object Dice.
    pub fn new(emoji: String, value: i64) -> Self {
        Self { emoji, value }
    }
}
