// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Dice;

impl Dice {
    /// This function creates an empty struct for the object Dice.
    pub fn new() -> Self {
        Self {
            emoji: "".to_string(),
            value: 0,
        }
    }
}
impl Default for Dice {
    fn default() -> Self {
        Self::new()
    }
}