// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Document;

impl Document {
    /// This function creates an empty struct for the object Document.
    pub fn new(file_id: String, file_unique_id: String) -> Self {
        Self {
            file_id,
            file_unique_id,
            thumbnail: None,
            file_name: None,
            mime_type: None,
            file_size: None,
        }
    }
}
