// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::EncryptedPassportElement;

impl EncryptedPassportElement {
    /// This function creates an empty struct for the object EncryptedPassportElement.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            data: None,
            phone_number: None,
            email: None,
            files: None,
            front_side: None,
            reverse_side: None,
            selfie: None,
            translation: None,
            hash: "".to_string(),
        }
    }
}
impl Default for EncryptedPassportElement {
    fn default() -> Self {
        Self::new()
    }
}