// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ForceReply;

impl ForceReply {
    /// This function creates an empty struct for the object ForceReply.
    pub fn new() -> Self {
        Self {
            force_reply: false,
            input_field_placeholder: None,
            selective: None,
        }
    }
}
impl Default for ForceReply {
    fn default() -> Self {
        Self::new()
    }
}