// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ForumTopicReopened;

impl ForumTopicReopened {
    /// This function creates an empty struct for the object ForumTopicReopened.
    pub fn new() -> Self {
        Self {}
    }
}
