// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ForumTopicEdited;

impl ForumTopicEdited {
    /// This function creates an empty struct for the object ForumTopicEdited.
    pub fn new() -> Self {
        Self {
            name: None,
            icon_custom_emoji_id: None,
        }
    }
}
