// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ForumTopicClosed;

impl ForumTopicClosed {
    /// This function creates an empty struct for the object ForumTopicClosed.
    pub fn new() -> Self {
        Self {}
    }
}
