// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::GameHighScore;
use crate::types::User;

impl GameHighScore {
    /// This function creates an empty struct for the object GameHighScore.
    pub fn new(position: i64, user: User, score: i64) -> Self {
        Self {
            position,
            user,
            score,
        }
    }
}
