// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Game;

impl Game {
    /// This function creates an empty struct for the object Game.
    pub fn new() -> Self {
        Self {
            title: "".to_string(),
            description: "".to_string(),
            photo: Vec::new(),
            text: None,
            text_entities: None,
            animation: None,
        }
    }
}
impl Default for Game {
    fn default() -> Self {
        Self::new()
    }
}