// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::GeneralForumTopicHidden;

impl GeneralForumTopicHidden {
    /// This function creates an empty struct for the object GeneralForumTopicHidden.
    pub fn new() -> Self {
        Self {
        }
    }
}