// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::GeneralForumTopicHidden;

impl GeneralForumTopicHidden {
    /// This function creates an empty struct for the object GeneralForumTopicHidden.
    pub fn new() -> Self {
        Self {}
    }
}
