// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::GiveawayCreated;

impl GiveawayCreated {
    /// This function creates an empty struct for the object GiveawayCreated.
    pub fn new() -> Self {
        Self {
        }
    }
}