// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InaccessibleMessage;
use crate::types::Chat;

impl InaccessibleMessage {
    /// This function creates an empty struct for the object InaccessibleMessage.
    pub fn new(chat: Chat, message_id: i64, date: i64) -> Self {
        Self {
            chat,
            message_id,
            date,
        }
    }
}