// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InlineKeyboardMarkup;

impl InlineKeyboardMarkup {
    /// This function creates an empty struct for the object InlineKeyboardMarkup.
    pub fn new() -> Self {
        Self {
            inline_keyboard: Vec::new(),
        }
    }
}