// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InlineQuery;
use crate::types::User;

impl InlineQuery {
    /// This function creates an empty struct for the object InlineQuery.
    pub fn new() -> Self {
        Self {
            id: "".to_string(),
            from: User::new(),
            query: "".to_string(),
            offset: "".to_string(),
            chat_type: None,
            location: None,
        }
    }
}
impl Default for InlineQuery {
    fn default() -> Self {
        Self::new()
    }
}