// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InlineKeyboardMarkup;
use crate::types::  InlineKeyboardButton;

impl InlineKeyboardMarkup {
    /// This function creates an empty struct for the object InlineKeyboardMarkup.
    pub fn new(inline_keyboard: Vec<Vec<InlineKeyboardButton>>) -> Self {
        Self {
            inline_keyboard,
        }
    }
}