// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMessageContent;
use crate::types::InputTextMessageContent;

impl InputMessageContent {
    /// This function creates an empty struct for the enum InputMessageContent.
    pub fn new() -> Self {
        Self::InputTextMessageContent(InputTextMessageContent::new())
    }

}
impl Default for InputMessageContent {
    fn default() -> Self {
        Self::new()
    }
}