// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMedia;
use crate::types::InputMediaAnimation;

impl InputMedia {
    /// This function creates an empty struct for the enum InputMedia.
    pub fn new() -> Self {
        Self::InputMediaAnimation(InputMediaAnimation::new())
    }

}
impl Default for InputMedia {
    fn default() -> Self {
        Self::new()
    }
}