// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputFile;
use crate::types::InputSticker;

impl InputSticker {
    /// This function creates an empty struct for the object InputSticker.
    pub fn new(sticker: String, emoji_list: Vec<String>) -> Self {
        Self {
            sticker,
            emoji_list,
            mask_position: None,
            keywords: None,
        }
    }
}
