// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputVenueMessageContent;

impl InputVenueMessageContent {
    /// This function creates an empty struct for the object InputVenueMessageContent.
    pub fn new() -> Self {
        Self {
            longitude: 0.0,
            title: "".to_string(),
            address: "".to_string(),
            foursquare_id: None,
            foursquare_type: None,
            google_place_id: None,
            google_place_type: None,
        }
    }
}
impl Default for InputVenueMessageContent {
    fn default() -> Self {
        Self::new()
    }
}