// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::InputTextMessageContent;

impl InputTextMessageContent {
    /// This function creates an empty struct for the object InputTextMessageContent.
    pub fn new(message_text: String) -> Self {
        Self {
            message_text,
            parse_mode: None,
            entities: None,
            link_preview_options: None,
        }
    }
}
