// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputSticker;

impl InputSticker {
    /// This function creates an empty struct for the object InputSticker.
    pub fn new() -> Self {
        Self {
            sticker: String::new(),
            emoji_list: Vec::new(),
            mask_position: None,
            keywords: None,
        }
    }
}
impl Default for InputSticker {
    fn default() -> Self {
        Self::new()
    }
}