// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::InputMediaDocument;

impl InputMediaDocument {
    /// This function creates an empty struct for the object InputMediaDocument.
    pub fn new(media: String) -> Self {
        Self {
            media,
            thumbnail: None,
            caption: None,
            parse_mode: None,
            caption_entities: None,
            disable_content_type_detection: None,
        }
    }
}
