// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMedia;

impl InputMedia {
    /// This function creates an empty struct for the object InputMedia.
    pub fn new() -> Self {
        Self {
        }
    }
}