// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMediaPhoto;

impl InputMediaPhoto {
    /// This function creates an empty struct for the object InputMediaPhoto.
    pub fn new(media: String) -> Self {
        Self {
            media,
            caption: None,
            parse_mode: None,
            caption_entities: None,
            has_spoiler: None,
        }
    }
}