// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputTextMessageContent;

impl Default for InputTextMessageContent {
    fn default() -> Self {
        Self::new()
    }
}

impl InputTextMessageContent {
    /// This function creates an empty struct for the object InputTextMessageContent.
    pub fn new() -> Self {
        Self {
            parse_mode: None,
            entities: None,
            link_preview_options: None,
        }
    }
}
