// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMediaAnimation;

impl InputMediaAnimation {
    /// This function creates an empty struct for the object InputMediaAnimation.
    pub fn new() -> Self {
        Self {
            media: "".to_string(),
            thumb: None,
            caption: None,
            parse_mode: None,
            caption_entities: None,
            width: None,
            height: None,
            duration: None,
        }
    }
}
impl Default for InputMediaAnimation {
    fn default() -> Self {
        Self::new()
    }
}