// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputMediaDocument;

impl InputMediaDocument {
    /// This function creates an empty struct for the object InputMediaDocument.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            media: "".to_string(),
            thumbnail: None,
            caption: None,
            parse_mode: None,
            caption_entities: None,
            disable_content_type_detection: None,
        }
    }
}
impl Default for InputMediaDocument {
    fn default() -> Self {
        Self::new()
    }
}
