// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputTextMessageContent;

impl InputTextMessageContent {
    /// This function creates an empty struct for the object InputTextMessageContent.
    pub fn new() -> Self {
        Self {
            parse_mode: None,
            entities: None,
            disable_web_page_preview: None,
        }
    }
}
impl Default for InputTextMessageContent {
    fn default() -> Self {
        Self::new()
    }
}