// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::InputFile;

impl InputFile {
    /// This function creates an empty struct for the object InputFile.
    pub fn new() -> Self {
        Self {}
    }
}
