// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Invoice;

impl Invoice {
    /// This function creates an empty struct for the object Invoice.
    pub fn new() -> Self {
        Self {
            title: "".to_string(),
            description: "".to_string(),
            start_parameter: "".to_string(),
            currency: "".to_string(),
            total_amount: 0,
        }
    }
}
impl Default for Invoice {
    fn default() -> Self {
        Self::new()
    }
}