// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::KeyboardButtonRequestChat;

impl KeyboardButtonRequestChat {
    /// This function creates an empty struct for the object KeyboardButtonRequestChat.
    pub fn new() -> Self {
        Self {
            request_id: 0,
            chat_is_channel: false,
            chat_is_forum: None,
            chat_has_username: None,
            chat_is_created: None,
            user_administrator_rights: None,
            bot_administrator_rights: None,
            bot_is_member: None,
        }
    }
}
impl Default for KeyboardButtonRequestChat {
    fn default() -> Self {
        Self::new()
    }
}