// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::KeyboardButton;

impl KeyboardButton {
    /// This function creates an empty struct for the object KeyboardButton.
    pub fn new(text: String) -> Self {
        Self {
            text,
            request_users: None,
            request_chat: None,
            request_contact: None,
            request_location: None,
            request_poll: None,
            web_app: None,
        }
    }
}
