// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::KeyboardButtonRequestUsers;

impl KeyboardButtonRequestUsers {
    /// This function creates an empty struct for the object KeyboardButtonRequestUsers.
    pub fn new(request_id: i64) -> Self {
        Self {
            request_id,
            user_is_bot: None,
            user_is_premium: None,
            max_quantity: None,
        }
    }
}
