// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::KeyboardButtonRequestUser;

impl KeyboardButtonRequestUser {
    /// This function creates an empty struct for the object KeyboardButtonRequestUser.
    pub fn new() -> Self {
        Self {
            request_id: 0,
            user_is_bot: None,
            user_is_premium: None,
        }
    }
}
impl Default for KeyboardButtonRequestUser {
    fn default() -> Self {
        Self::new()
    }
}