// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::KeyboardButtonPollType;

impl KeyboardButtonPollType {
    /// This function creates an empty struct for the object KeyboardButtonPollType.
    pub fn new() -> Self {
        Self {
            r#type: None,
        }
    }
}
impl Default for KeyboardButtonPollType {
    fn default() -> Self {
        Self::new()
    }
}