// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::KeyboardButtonPollType;

impl KeyboardButtonPollType {
    /// This function creates an empty struct for the object KeyboardButtonPollType.
    pub fn new() -> Self {
        Self { r#type: None }
    }
}
