// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::LabeledPrice;

impl LabeledPrice {
    /// This function creates an empty struct for the object LabeledPrice.
    pub fn new(label: String, amount: i64) -> Self {
        Self { label, amount }
    }
}
