// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::LinkPreviewOptions;

impl LinkPreviewOptions {
    /// This function creates an empty struct for the object LinkPreviewOptions.
    pub fn new() -> Self {
        Self {
            is_disabled: None,
            url: None,
            prefer_small_media: None,
            prefer_large_media: None,
            show_above_text: None,
        }
    }
}