// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Location;

impl Location {
    /// This function creates an empty struct for the object Location.
    pub fn new() -> Self {
        Self {
            longitude: 0.0,
            latitude: 0.0,
            horizontal_accuracy: None,
            live_period: None,
            heading: None,
            proximity_alert_radius: None,
        }
    }
}
impl Default for Location {
    fn default() -> Self {
        Self::new()
    }
}