// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::LoginUrl;

impl LoginUrl {
    /// This function creates an empty struct for the object LoginUrl.
    pub fn new() -> Self {
        Self {
            url: "".to_string(),
            forward_text: None,
            bot_username: None,
            request_write_access: None,
        }
    }
}
impl Default for LoginUrl {
    fn default() -> Self {
        Self::new()
    }
}