// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MaskPosition;

impl MaskPosition {
    /// This function creates an empty struct for the object MaskPosition.
    pub fn new() -> Self {
        Self {
            point: "".to_string(),
            x_shift: 0.0,
            y_shift: 0.0,
            scale: 0.0,
        }
    }
}
impl Default for MaskPosition {
    fn default() -> Self {
        Self::new()
    }
}