// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MenuButton;
use crate::types::MenuButtonCommands;

impl MenuButton {
    /// This function creates an empty struct for the enum MenuButton.
    pub fn new() -> Self {
        Self::MenuButtonCommands(MenuButtonCommands::new())
    }

}
impl Default for MenuButton {
    fn default() -> Self {
        Self::new()
    }
}