// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MenuButton;

impl MenuButton {
    /// This function creates an empty struct for the object MenuButton.
    pub fn new() -> Self {
        Self {}
    }
}
impl Default for MenuButton {
    fn default() -> Self {
        Self::new()
    }
}
