// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MenuButtonWebApp;
use crate::types::WebAppInfo;

impl MenuButtonWebApp {
    /// This function creates an empty struct for the object MenuButtonWebApp.
    pub fn new() -> Self {
        Self {
            text: "".to_string(),
            web_app: WebAppInfo::new(),
        }
    }
}
impl Default for MenuButtonWebApp {
    fn default() -> Self {
        Self::new()
    }
}