// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MenuButtonCommands;

impl MenuButtonCommands {
    /// This function creates an empty struct for the object MenuButtonCommands.
    pub fn new() -> Self {
        Self {
        }
    }
}
impl Default for MenuButtonCommands {
    fn default() -> Self {
        Self::new()
    }
}