// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::MessageEntity;

impl MessageEntity {
    /// This function creates an empty struct for the object MessageEntity.
    pub fn new(r#type: String, offset: i64, length: i64) -> Self {
        Self {
            r#type,
            offset,
            length,
            url: None,
            user: None,
            language: None,
            custom_emoji_id: None,
        }
    }
}
