// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MessageOriginChat;
use crate::types::Chat;

impl MessageOriginChat {
    /// This function creates an empty struct for the object MessageOriginChat.
    pub fn new(date: i64, sender_chat: Chat) -> Self {
        Self {
            date,
            sender_chat,
            author_signature: None,
        }
    }
}