// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MessageEntity;

impl MessageEntity {
    /// This function creates an empty struct for the object MessageEntity.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            offset: 0,
            length: 0,
            url: None,
            user: None,
            language: None,
            custom_emoji_id: None,
        }
    }
}
impl Default for MessageEntity {
    fn default() -> Self {
        Self::new()
    }
}