// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Chat;
use crate::types::MessageOriginChat;

impl MessageOriginChat {
    /// This function creates an empty struct for the object MessageOriginChat.
    pub fn new(date: i64, sender_chat: Chat) -> Self {
        Self {
            date,
            sender_chat,
            author_signature: None,
        }
    }
}
