// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MessageOriginHiddenUser;

impl MessageOriginHiddenUser {
    /// This function creates an empty struct for the object MessageOriginHiddenUser.
    pub fn new(date: i64, sender_user_name: String) -> Self {
        Self {
            date,
            sender_user_name,
        }
    }
}
