// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::EncryptedCredentials;
use crate::types::EncryptedPassportElement;
use crate::types::PassportData;

impl PassportData {
    /// This function creates an empty struct for the object PassportData.
    pub fn new(data: Vec<EncryptedPassportElement>, credentials: EncryptedCredentials) -> Self {
        Self { data, credentials }
    }
}
