// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorFile;

impl PassportElementErrorFile {
    /// This function creates an empty struct for the object PassportElementErrorFile.
    pub fn new(r#type: String, file_hash: String, message: String) -> Self {
        Self {
            r#type,
            file_hash,
            message,
        }
    }
}