// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::PassportElementErrorFrontSide;

impl PassportElementErrorFrontSide {
    /// This function creates an empty struct for the object PassportElementErrorFrontSide.
    pub fn new(r#type: String, file_hash: String, message: String) -> Self {
        Self {
            r#type,
            file_hash,
            message,
        }
    }
}
