// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportData;
use crate::types:: EncryptedPassportElement;
use crate::types::EncryptedCredentials;

impl PassportData {
    /// This function creates an empty struct for the object PassportData.
    pub fn new(data: Vec<EncryptedPassportElement>, credentials: EncryptedCredentials) -> Self {
        Self {
            data,
            credentials,
        }
    }
}