// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::PassportFile;

impl PassportFile {
    /// This function creates an empty struct for the object PassportFile.
    pub fn new(file_id: String, file_unique_id: String, file_size: i64, file_date: i64) -> Self {
        Self {
            file_id,
            file_unique_id,
            file_size,
            file_date,
        }
    }
}
