// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorReverseSide;

impl PassportElementErrorReverseSide {
    /// This function creates an empty struct for the object PassportElementErrorReverseSide.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            file_hash: "".to_string(),
            message: "".to_string(),
        }
    }
}
impl Default for PassportElementErrorReverseSide {
    fn default() -> Self {
        Self::new()
    }
}