// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorReverseSide;

impl PassportElementErrorReverseSide {
    /// This function creates an empty struct for the object PassportElementErrorReverseSide.
    pub fn new(source: String, r#type: String, file_hash: String, message: String) -> Self {
        Self {
            source,
            r#type,
            file_hash,
            message,
        }
    }
}
