// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementError;

impl PassportElementError {
    /// This function creates an empty struct for the object PassportElementError.
    pub fn new() -> Self {
        Self {
        }
    }
}