// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorSelfie;

impl PassportElementErrorSelfie {
    /// This function creates an empty struct for the object PassportElementErrorSelfie.
    pub fn new(r#type: String, file_hash: String, message: String) -> Self {
        Self {
            r#type,
            file_hash,
            message,
        }
    }
}
