// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorDataField;

impl PassportElementErrorDataField {
    /// This function creates an empty struct for the object PassportElementErrorDataField.
    pub fn new(r#type: String, field_name: String, data_hash: String, message: String) -> Self {
        Self {
            r#type,
            field_name,
            data_hash,
            message,
        }
    }
}