// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::PassportElementErrorUnspecified;

impl PassportElementErrorUnspecified {
    /// This function creates an empty struct for the object PassportElementErrorUnspecified.
    pub fn new(r#type: String, element_hash: String, message: String) -> Self {
        Self {
            r#type,
            element_hash,
            message,
        }
    }
}
