// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorDataField;

impl PassportElementErrorDataField {
    /// This function creates an empty struct for the object PassportElementErrorDataField.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            field_name: "".to_string(),
            data_hash: "".to_string(),
            message: "".to_string(),
        }
    }
}
impl Default for PassportElementErrorDataField {
    fn default() -> Self {
        Self::new()
    }
}