// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorFiles;

impl PassportElementErrorFiles {
    /// This function creates an empty struct for the object PassportElementErrorFiles.
    pub fn new(r#type: String, file_hashes: Vec<String>, message: String) -> Self {
        Self {
            r#type,
            file_hashes,
            message,
        }
    }
}
