// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PassportElementErrorFiles;

impl PassportElementErrorFiles {
    /// This function creates an empty struct for the object PassportElementErrorFiles.
    pub fn new() -> Self {
        Self {
            r#type: "".to_string(),
            file_hashes: Vec::new(),
            message: "".to_string(),
        }
    }
}
impl Default for PassportElementErrorFiles {
    fn default() -> Self {
        Self::new()
    }
}