// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::PollAnswer;

impl PollAnswer {
    /// This function creates an empty struct for the object PollAnswer.
    pub fn new(poll_id: String, option_ids: Vec<i64>) -> Self {
        Self {
            poll_id,
            voter_chat: None,
            user: None,
            option_ids,
        }
    }
}
