// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PollOption;

impl PollOption {
    /// This function creates an empty struct for the object PollOption.
    pub fn new(text: String, voter_count: i64) -> Self {
        Self {
            text,
            voter_count,
        }
    }
}