// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::PollOption;

impl PollOption {
    /// This function creates an empty struct for the object PollOption.
    pub fn new() -> Self {
        Self {
            text: "".to_string(),
            voter_count: 0,
        }
    }
}
impl Default for PollOption {
    fn default() -> Self {
        Self::new()
    }
}