// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ProximityAlertTriggered;
use crate::types::User;

impl ProximityAlertTriggered {
    /// This function creates an empty struct for the object ProximityAlertTriggered.
    pub fn new() -> Self {
        Self {
            traveler: User::new(),
            watcher: User::new(),
            distance: 0,
        }
    }
}
impl Default for ProximityAlertTriggered {
    fn default() -> Self {
        Self::new()
    }
}