// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ReactionCount;
use crate::types::ReactionType;

impl ReactionCount {
    /// This function creates an empty struct for the object ReactionCount.
    pub fn new(r#type: ReactionType, total_count: i64) -> Self {
        Self {
            r#type,
            total_count,
        }
    }
}