// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ReactionTypeCustomEmoji;

impl ReactionTypeCustomEmoji {
    /// This function creates an empty struct for the object ReactionTypeCustomEmoji.
    pub fn new(custom_emoji_id: String) -> Self {
        Self { custom_emoji_id }
    }
}
