// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ReactionTypeEmoji;

impl ReactionTypeEmoji {
    /// This function creates an empty struct for the object ReactionTypeEmoji.
    pub fn new(emoji: String) -> Self {
        Self { emoji }
    }
}
