// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ReplyParameters;

impl ReplyParameters {
    /// This function creates an empty struct for the object ReplyParameters.
    pub fn new(message_id: i64) -> Self {
        Self {
            message_id,
            chat_id: None,
            allow_sending_without_reply: None,
            quote: None,
            quote_parse_mode: None,
            quote_entities: None,
            quote_position: None,
        }
    }
}
