// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ReplyKeyboardRemove;

impl ReplyKeyboardRemove {
    /// This function creates an empty struct for the object ReplyKeyboardRemove.
    pub fn new(remove_keyboard: bool) -> Self {
        Self {
            remove_keyboard,
            selective: None,
        }
    }
}