// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ReplyKeyboardRemove;

impl ReplyKeyboardRemove {
    /// This function creates an empty struct for the object ReplyKeyboardRemove.
    pub fn new() -> Self {
        Self {
            remove_keyboard: false,
            selective: None,
        }
    }
}
impl Default for ReplyKeyboardRemove {
    fn default() -> Self {
        Self::new()
    }
}