// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ReplyKeyboardMarkup;
use crate::types::  KeyboardButton;

impl ReplyKeyboardMarkup {
    /// This function creates an empty struct for the object ReplyKeyboardMarkup.
    pub fn new(keyboard: Vec<Vec<KeyboardButton>>) -> Self {
        Self {
            keyboard,
            is_persistent: None,
            resize_keyboard: None,
            one_time_keyboard: None,
            input_field_placeholder: None,
            selective: None,
        }
    }
}