// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::SentWebAppMessage;

impl SentWebAppMessage {
    /// This function creates an empty struct for the object SentWebAppMessage.
    pub fn new() -> Self {
        Self {
            inline_message_id: None,
        }
    }
}
