// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ShippingOption;
use crate::types:: LabeledPrice;

impl ShippingOption {
    /// This function creates an empty struct for the object ShippingOption.
    pub fn new(id: String, title: String, prices: Vec<LabeledPrice>) -> Self {
        Self {
            id,
            title,
            prices,
        }
    }
}