// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ShippingAddress;

impl ShippingAddress {
    /// This function creates an empty struct for the object ShippingAddress.
    pub fn new() -> Self {
        Self {
            country_code: "".to_string(),
            state: "".to_string(),
            city: "".to_string(),
            street_line1: "".to_string(),
            street_line2: "".to_string(),
            post_code: "".to_string(),
        }
    }
}
impl Default for ShippingAddress {
    fn default() -> Self {
        Self::new()
    }
}