// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::ShippingQuery;
use crate::types::User;
use crate::types::ShippingAddress;

impl ShippingQuery {
    /// This function creates an empty struct for the object ShippingQuery.
    pub fn new() -> Self {
        Self {
            id: "".to_string(),
            from: User::new(),
            invoice_payload: "".to_string(),
            shipping_address: ShippingAddress::new(),
        }
    }
}
impl Default for ShippingQuery {
    fn default() -> Self {
        Self::new()
    }
}