// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Chat;
use crate::types::Story;

impl Story {
    /// This function creates an empty struct for the object Story.
    pub fn new(chat: Chat, id: i64) -> Self {
        Self { chat, id }
    }
}
