// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Story;

impl Default for Story {
    fn default() -> Self {
        Self::new()
    }
}

impl Story {
    /// This function creates an empty struct for the object Story.
    pub fn new() -> Self {
        Self {}
    }
}
