// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::SwitchInlineQueryChosenChat;

impl SwitchInlineQueryChosenChat {
    /// This function creates an empty struct for the object SwitchInlineQueryChosenChat.
    pub fn new() -> Self {
        Self {
            query: None,
            allow_user_chats: None,
            allow_bot_chats: None,
            allow_group_chats: None,
            allow_channel_chats: None,
        }
    }
}
