// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::UserShared;

impl UserShared {
    /// This function creates an empty struct for the object UserShared.
    pub fn new() -> Self {
        Self {
            request_id: 0,
            user_id: 0,
        }
    }
}
impl Default for UserShared {
    fn default() -> Self {
        Self::new()
    }
}