// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::ChatBoost;
use crate::types::UserChatBoosts;

impl UserChatBoosts {
    /// This function creates an empty struct for the object UserChatBoosts.
    pub fn new(boosts: Vec<ChatBoost>) -> Self {
        Self { boosts }
    }
}
