// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::UserChatBoosts;
use crate::types:: ChatBoost;

impl UserChatBoosts {
    /// This function creates an empty struct for the object UserChatBoosts.
    pub fn new(boosts: Vec<ChatBoost>) -> Self {
        Self {
            boosts,
        }
    }
}