// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::UserProfilePhotos;
use crate::types::  PhotoSize;

impl UserProfilePhotos {
    /// This function creates an empty struct for the object UserProfilePhotos.
    pub fn new(total_count: i64, photos: Vec<Vec<PhotoSize>>) -> Self {
        Self {
            total_count,
            photos,
        }
    }
}