// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Venue;
use crate::types::Location;

impl Venue {
    /// This function creates an empty struct for the object Venue.
    pub fn new() -> Self {
        Self {
            location: Location::new(),
            title: "".to_string(),
            address: "".to_string(),
            foursquare_id: None,
            foursquare_type: None,
            google_place_id: None,
            google_place_type: None,
        }
    }
}
impl Default for Venue {
    fn default() -> Self {
        Self::new()
    }
}