// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VideoChatParticipantsInvited;

impl VideoChatParticipantsInvited {
    /// This function creates an empty struct for the object VideoChatParticipantsInvited.
    pub fn new() -> Self {
        Self {
            users: Vec::new(),
        }
    }
}
impl Default for VideoChatParticipantsInvited {
    fn default() -> Self {
        Self::new()
    }
}