// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::VideoChatEnded;

impl VideoChatEnded {
    /// This function creates an empty struct for the object VideoChatEnded.
    pub fn new(duration: i64) -> Self {
        Self { duration }
    }
}
