// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VideoChatParticipantsInvited;
use crate::types:: User;

impl VideoChatParticipantsInvited {
    /// This function creates an empty struct for the object VideoChatParticipantsInvited.
    pub fn new(users: Vec<User>) -> Self {
        Self {
            users,
        }
    }
}