// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::User;
use crate::types::VideoChatParticipantsInvited;

impl VideoChatParticipantsInvited {
    /// This function creates an empty struct for the object VideoChatParticipantsInvited.
    pub fn new(users: Vec<User>) -> Self {
        Self { users }
    }
}
