// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::VideoChatScheduled;

impl VideoChatScheduled {
    /// This function creates an empty struct for the object VideoChatScheduled.
    pub fn new(start_date: i64) -> Self {
        Self { start_date }
    }
}
