// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VideoNote;

impl VideoNote {
    /// This function creates an empty struct for the object VideoNote.
    pub fn new() -> Self {
        Self {
            file_id: "".to_string(),
            file_unique_id: "".to_string(),
            length: 0,
            duration: 0,
            thumb: None,
            file_size: None,
        }
    }
}
impl Default for VideoNote {
    fn default() -> Self {
        Self::new()
    }
}