// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VideoChatStarted;

impl VideoChatStarted {
    /// This function creates an empty struct for the object VideoChatStarted.
    pub fn new() -> Self {
        Self {
        }
    }
}
impl Default for VideoChatStarted {
    fn default() -> Self {
        Self::new()
    }
}