// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Video;

impl Video {
    /// This function creates an empty struct for the object Video.
    pub fn new() -> Self {
        Self {
            file_id: "".to_string(),
            file_unique_id: "".to_string(),
            width: 0,
            height: 0,
            duration: 0,
            thumb: None,
            file_name: None,
            mime_type: None,
            file_size: None,
        }
    }
}
impl Default for Video {
    fn default() -> Self {
        Self::new()
    }
}