// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VideoNote;

impl VideoNote {
    /// This function creates an empty struct for the object VideoNote.
    pub fn new(file_id: String, file_unique_id: String, length: i64, duration: i64) -> Self {
        Self {
            file_id,
            file_unique_id,
            length,
            duration,
            thumbnail: None,
            file_size: None,
        }
    }
}
