// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VoiceChatStarted;

impl VoiceChatStarted {
    /// This function creates an empty struct for the object VoiceChatStarted.
    pub fn new() -> Self {
        Self {
        }
    }
}
impl Default for VoiceChatStarted {
    fn default() -> Self {
        Self::new()
    }
}