// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::VoiceChatEnded;

impl VoiceChatEnded {
    /// This function creates an empty struct for the object VoiceChatEnded.
    pub fn new() -> Self {
        Self {
            duration: 0,
        }
    }
}
impl Default for VoiceChatEnded {
    fn default() -> Self {
        Self::new()
    }
}