// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::WebAppInfo;

impl WebAppInfo {
    /// This function creates an empty struct for the object WebAppInfo.
    pub fn new() -> Self {
        Self {
            url: "".to_string(),
        }
    }
}
impl Default for WebAppInfo {
    fn default() -> Self {
        Self::new()
    }
}