// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::WebAppInfo;

impl WebAppInfo {
    /// This function creates an empty struct for the object WebAppInfo.
    pub fn new(url: String) -> Self {
        Self { url }
    }
}
