// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::WebAppData;

impl WebAppData {
    /// This function creates an empty struct for the object WebAppData.
    pub fn new(data: String, button_text: String) -> Self {
        Self {
            data,
            button_text,
        }
    }
}