// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::WriteAccessAllowed;

impl Default for WriteAccessAllowed {
    fn default() -> Self {
        Self::new()
    }
}

impl WriteAccessAllowed {
    /// This function creates an empty struct for the object WriteAccessAllowed.
    pub fn new() -> Self {
        Self {
            from_request: None,
            web_app_name: None,
            from_attachment_menu: None,
        }
    }
}
