// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// This object represents the bot's description.
/// <https://core.telegram.org/bots/api#botdescription>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BotDescription {
    /// The bot's description
    pub description: String,
}