// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::User;
use serde::{Deserialize, Serialize};


/// Represents a chat member that owns the chat and has all administrator privileges.
/// <https://core.telegram.org/bots/api#chatmemberowner>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ChatMemberOwner {
    /// Information about the user
    pub user: User,
    /// True, if the user's presence in the chat is hidden
    pub is_anonymous: bool,
    /// Optional. Custom title for this user
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_title: Option<String>,
}