// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{Chat, ChatBoostSource};
use serde::{Deserialize, Serialize};

/// This object represents a boost removed from a chat.
/// <https://core.telegram.org/bots/api#chatboostremoved>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ChatBoostRemoved {
    /// Chat which was boosted
    pub chat: Chat,
    /// Unique identifier of the boost
    pub boost_id: String,
    /// Point in time (Unix timestamp) when the boost was removed
    pub remove_date: i64,
    /// Source of the removed boost
    pub source: ChatBoostSource,
}
