// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{ChatMemberOwner, ChatMemberAdministrator, ChatMemberMember, ChatMemberRestricted, ChatMemberLeft, ChatMemberBanned};
use serde::{Deserialize, Serialize};


/// This object contains information about one member of a chat. Currently, the following 6 types of chat members are supported:
/// - ChatMemberOwner
/// - ChatMemberAdministrator
/// - ChatMemberMember
/// - ChatMemberRestricted
/// - ChatMemberLeft
/// - ChatMemberBanned
/// <https://core.telegram.org/bots/api#chatmember>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "status")]
pub enum ChatMember {
    #[serde(rename = "creator")]
    ChatMemberOwner(ChatMemberOwner),
    #[serde(rename = "administrator")]
    ChatMemberAdministrator(ChatMemberAdministrator),
    #[serde(rename = "member")]
    ChatMemberMember(ChatMemberMember),
    #[serde(rename = "restricted")]
    ChatMemberRestricted(ChatMemberRestricted),
    #[serde(rename = "left")]
    ChatMemberLeft(ChatMemberLeft),
    #[serde(rename = "kicked")]
    ChatMemberBanned(ChatMemberBanned),
}
