// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{Chat, ChatBoost};
use serde::{Deserialize, Serialize};

/// This object represents a boost added to a chat or changed.
/// <https://core.telegram.org/bots/api#chatboostupdated>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ChatBoostUpdated {
    /// Chat which was boosted
    pub chat: Chat,
    /// Infomation about the chat boost
    pub boost: ChatBoost,
}
