// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{
    ChatMemberAdministrator, ChatMemberBanned, ChatMemberLeft, ChatMemberMember, ChatMemberOwner,
    ChatMemberRestricted,
};
use serde::{Deserialize, Serialize};

/// This object contains information about one member of a chat. Currently, the following 6 types of chat members are supported:
/// - ChatMemberOwner
/// - ChatMemberAdministrator
/// - ChatMemberMember
/// - ChatMemberRestricted
/// - ChatMemberLeft
/// - ChatMemberBanned
/// <https://core.telegram.org/bots/api#chatmember>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum ChatMember {
    ChatMemberOwner(ChatMemberOwner),
    ChatMemberAdministrator(ChatMemberAdministrator),
    ChatMemberMember(ChatMemberMember),
    ChatMemberRestricted(ChatMemberRestricted),
    ChatMemberLeft(ChatMemberLeft),
    ChatMemberBanned(ChatMemberBanned),
}
