// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// This object represents a service message about a forum topic closed in the chat. Currently holds no information.
/// <https://core.telegram.org/bots/api#forumtopicclosed>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ForumTopicClosed {}
