// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Chat;
use serde::{Deserialize, Serialize};


/// This object describes a message that was deleted or is otherwise inaccessible to the bot.
/// <https://core.telegram.org/bots/api#inaccessiblemessage>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct InaccessibleMessage {
    /// Chat the message belonged to
    pub chat: Chat,
    /// Unique message identifier inside the chat
    pub message_id: i64,
    /// Always 0. The field can be used to differentiate regular and inaccessible messages.
    pub date: i64,
}