// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{InputMediaAnimation, InputMediaDocument, InputMediaAudio, InputMediaPhoto, InputMediaVideo};
use serde::{Deserialize, Serialize};


/// This object represents the content of a media message to be sent. It should be one of
/// - InputMediaAnimation
/// - InputMediaDocument
/// - InputMediaAudio
/// - InputMediaPhoto
/// - InputMediaVideo
/// <https://core.telegram.org/bots/api#inputmedia>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum InputMedia {
    #[serde(rename = "animation")]
    InputMediaAnimation(InputMediaAnimation),
    #[serde(rename = "document")]
    InputMediaDocument(InputMediaDocument),
    #[serde(rename = "audio")]
    InputMediaAudio(InputMediaAudio),
    #[serde(rename = "photo")]
    InputMediaPhoto(InputMediaPhoto),
    #[serde(rename = "video")]
    InputMediaVideo(InputMediaVideo),
}
