// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{Message, InaccessibleMessage};
use serde::Serialize;


/// This object describes a message that can be inaccessible to the bot. It can be one of
/// - Message
/// - InaccessibleMessage
/// <https://core.telegram.org/bots/api#maybeinaccessiblemessage>
#[derive(Serialize, Debug, Clone)]
pub enum MaybeInaccessibleMessage {
    Message(Message),
    InaccessibleMessage(InaccessibleMessage),
}
