// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{MenuButtonCommands, MenuButtonWebApp, MenuButtonDefault};
use serde::{Deserialize, Serialize};


/// This object describes the bot's menu button in a private chat. It should be one of
/// - MenuButtonCommands
/// - MenuButtonWebApp
/// - MenuButtonDefault
/// If a menu button other than MenuButtonDefault is set for a private chat, then it is applied in the chat. Otherwise the default menu button is applied. By default, the menu button opens the list of bot commands.
/// <https://core.telegram.org/bots/api#menubutton>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum MenuButton {
    #[serde(rename = "commands")]
    MenuButtonCommands(MenuButtonCommands),
    #[serde(rename = "web_app")]
    MenuButtonWebApp(MenuButtonWebApp),
    #[serde(rename = "default")]
    MenuButtonDefault(MenuButtonDefault),
}
