// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// The message was originally sent by an unknown user.
/// <https://core.telegram.org/bots/api#messageoriginhiddenuser>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct MessageOriginHiddenUser {
    /// Date the message was sent originally in Unix time
    pub date: i64,
    /// Name of the user that sent the message originally
    pub sender_user_name: String,
}