// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// This object represents a unique message identifier.
/// <https://core.telegram.org/bots/api#messageid>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct MessageId {
    /// Unique message identifier
    pub message_id: i64,
}