// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{Chat, ReactionCount};
use serde::{Deserialize, Serialize};


/// This object represents reaction changes on a message with anonymous reactions.
/// <https://core.telegram.org/bots/api#messagereactioncountupdated>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct MessageReactionCountUpdated {
    /// The chat containing the message
    pub chat: Chat,
    /// Unique message identifier inside the chat
    pub message_id: i64,
    /// Date of the change in Unix time
    pub date: i64,
    /// List of reactions that are present on the message
    pub reactions: Vec<ReactionCount>,
}