// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{
    MessageOriginChannel, MessageOriginChat, MessageOriginHiddenUser, MessageOriginUser,
};
use serde::{Deserialize, Serialize};

/// This object describes the origin of a message. It can be one of
/// - MessageOriginUser
/// - MessageOriginHiddenUser
/// - MessageOriginChat
/// - MessageOriginChannel
/// <https://core.telegram.org/bots/api#messageorigin>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum MessageOrigin {
    #[serde(rename = "user")]
    MessageOriginUser(MessageOriginUser),
    #[serde(rename = "hidden_user")]
    MessageOriginHiddenUser(MessageOriginHiddenUser),
    #[serde(rename = "chat")]
    MessageOriginChat(MessageOriginChat),
    #[serde(rename = "channel")]
    MessageOriginChannel(MessageOriginChannel),
}
