// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// Represents an issue in one of the data fields that was provided by the user. The error is considered resolved when the field's value changes.
/// <https://core.telegram.org/bots/api#passportelementerrordatafield>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PassportElementErrorDataField {
    /// The section of the user's Telegram Passport which has the error, one of "personal_details", "passport", "driver_license", "identity_card", "internal_passport", "address"
    pub r#type: String,
    /// Name of the data field which has the error
    pub field_name: String,
    /// Base64-encoded data hash
    pub data_hash: String,
    /// Error message
    pub message: String,
}