// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// Represents an issue with a document scan. The error is considered resolved when the file with the document scan changes.
/// <https://core.telegram.org/bots/api#passportelementerrorfile>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PassportElementErrorFile {
    /// The section of the user's Telegram Passport which has the issue, one of "utility_bill", "bank_statement", "rental_agreement", "passport_registration", "temporary_registration"
    pub r#type: String,
    /// Base64-encoded file hash
    pub file_hash: String,
    /// Error message
    pub message: String,
}