// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{PassportElementErrorDataField, PassportElementErrorFrontSide, PassportElementErrorReverseSide, PassportElementErrorSelfie, PassportElementErrorFile, PassportElementErrorFiles, PassportElementErrorTranslationFile, PassportElementErrorTranslationFiles, PassportElementErrorUnspecified};
use serde::{Deserialize, Serialize};


/// This object represents an error in the Telegram Passport element which was submitted that should be resolved by the user. It should be one of:
/// - PassportElementErrorDataField
/// - PassportElementErrorFrontSide
/// - PassportElementErrorReverseSide
/// - PassportElementErrorSelfie
/// - PassportElementErrorFile
/// - PassportElementErrorFiles
/// - PassportElementErrorTranslationFile
/// - PassportElementErrorTranslationFiles
/// - PassportElementErrorUnspecified
/// <https://core.telegram.org/bots/api#passportelementerror>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "source")]
pub enum PassportElementError {
    #[serde(rename = "data")]
    PassportElementErrorDataField(PassportElementErrorDataField),
    #[serde(rename = "front_side")]
    PassportElementErrorFrontSide(PassportElementErrorFrontSide),
    #[serde(rename = "reverse_side")]
    PassportElementErrorReverseSide(PassportElementErrorReverseSide),
    #[serde(rename = "selfie")]
    PassportElementErrorSelfie(PassportElementErrorSelfie),
    #[serde(rename = "file")]
    PassportElementErrorFile(PassportElementErrorFile),
    #[serde(rename = "files")]
    PassportElementErrorFiles(PassportElementErrorFiles),
    #[serde(rename = "translation_file")]
    PassportElementErrorTranslationFile(PassportElementErrorTranslationFile),
    #[serde(rename = "translation_files")]
    PassportElementErrorTranslationFiles(PassportElementErrorTranslationFiles),
    #[serde(rename = "unspecified")]
    PassportElementErrorUnspecified(PassportElementErrorUnspecified),
}
