// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// Represents an issue in an unspecified place. The error is considered resolved when new data is added.
/// <https://core.telegram.org/bots/api#passportelementerrorunspecified>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PassportElementErrorUnspecified {
    /// Type of element of the user's Telegram Passport which has the issue
    pub r#type: String,
    /// Base64-encoded element hash
    pub element_hash: String,
    /// Error message
    pub message: String,
}