// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// Represents an issue with the reverse side of a document. The error is considered resolved when the file with reverse side of the document changes.
/// <https://core.telegram.org/bots/api#passportelementerrorreverseside>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PassportElementErrorReverseSide {
    /// The section of the user's Telegram Passport which has the issue, one of "driver_license", "identity_card"
    pub r#type: String,
    /// Base64-encoded hash of the file with the reverse side of the document
    pub file_hash: String,
    /// Error message
    pub message: String,
}