// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// This object contains information about one answer option in a poll.
/// <https://core.telegram.org/bots/api#polloption>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PollOption {
    /// Option text, 1-100 characters
    pub text: String,
    /// Number of users that voted for this option
    pub voter_count: i64,
}