// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{ReactionTypeEmoji, ReactionTypeCustomEmoji};
use serde::{Deserialize, Serialize};


/// This object describes the type of a reaction. Currently, it can be one of
/// - ReactionTypeEmoji
/// - ReactionTypeCustomEmoji
/// <https://core.telegram.org/bots/api#reactiontype>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum ReactionType {
    #[serde(rename = "emoji")]
    ReactionTypeEmoji(ReactionTypeEmoji),
    #[serde(rename = "custom_emoji")]
    ReactionTypeCustomEmoji(ReactionTypeCustomEmoji),
}
