// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The reaction is based on a custom emoji.
/// <https://core.telegram.org/bots/api#reactiontypecustomemoji>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ReactionTypeCustomEmoji {
    /// Custom emoji identifier
    pub custom_emoji_id: String,
}
