// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// Describes an inline message sent by a Web App on behalf of a user.
/// <https://core.telegram.org/bots/api#sentwebappmessage>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SentWebAppMessage {
    /// Optional. Identifier of the sent inline message. Available only if there is an inline keyboard attached to the message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inline_message_id: Option<String>,
}