// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::LabeledPrice;
use serde::{Deserialize, Serialize};


/// This object represents one shipping option.
/// <https://core.telegram.org/bots/api#shippingoption>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ShippingOption {
    /// Shipping option identifier
    pub id: String,
    /// Option title
    pub title: String,
    /// List of price portions
    pub prices: Vec<LabeledPrice>,
}