// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// This object represents a message about a forwarded story in the chat. Currently holds no information.
/// <https://core.telegram.org/bots/api#story>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Story {}
