// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Chat;
use serde::{Deserialize, Serialize};

/// This object represents a story.
/// <https://core.telegram.org/bots/api#story>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Story {
    /// Chat that posted the story
    pub chat: Chat,
    /// Unique identifier for the story in the chat
    pub id: i64,
}
