// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};


/// This object represents a service message about a user allowing a bot added to the attachment menu to write messages. Currently holds no information.
/// <https://core.telegram.org/bots/api#writeaccessallowed>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct WriteAccessAllowed {
}