//! FerrisGram is an asynchronous autogenerated wrapper for the Telegram Bot API written in Rust. This library provides all the methods and types that are available on the official Telegram Bot API.

pub mod bot;
pub mod error;
pub mod ext;
pub mod methods;
pub mod types;
pub use bot::*;
mod helpers;
pub mod helpers_ext;

pub static DEFAULT_API_URL: &str = "https://api.telegram.org";
